language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
before_deploy: npm run build
deploy:
  provider: npm
  email: trembl.ben@gmail.com
  on:
    tags: true
    repo: @reactivestack/react-library-starterkit
