// flow-typed signature: 06e620978cceaf7c9c4224f80e653cbd
// flow-typed version: <<STUB>>/eslint-config-reactivestack_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-reactivestack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-reactivestack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-reactivestack/index' {
  declare module.exports: $Exports<'eslint-config-reactivestack'>;
}
declare module 'eslint-config-reactivestack/index.js' {
  declare module.exports: $Exports<'eslint-config-reactivestack'>;
}
